# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cable:
    <<: *default
    # If you want to store cable data in the same DB:
    url: <%= ENV["DATABASE_URL"] %>
    # Optionally specify separate migrations path if you have them:
    # migrations_paths: db/cable_migrate
