default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: research_webapp_development
  # Docker-specific settings for local dev:
  host: <%= ENV.fetch("DATABASE_HOST", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

test:
  <<: *default
  database: research_webapp_test
  # Same Docker settings for test, or override if needed:
  host: <%= ENV.fetch("DATABASE_HOST", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", 5432) %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>

production:
  primary:
    <<: *default
    # Heroku uses DATABASE_URL for the main DB:
    url: <%= ENV["DATABASE_URL"] %>

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    # migrations_paths: db/queue_migrate

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    # migrations_paths: db/cache_migrate

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    # migrations_paths: db/cable_migrate
